### ISSUE TITLE
Support slevomat/coding-standard 6.1.*

### ISSUE THREAD

**Issue by krns** [consistence/coding-standard#62]
Because of this [commit](https://github.com/consistence/coding-standard/commit/1d6dc1f638fdd293333939634b7021c363e82993#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L16-R16), the last minor update of [slevomat/coding-standard](https://github.com/slevomat/coding-standard/releases) is not supported anymore.

**Comment by radimvaculik** [comment]
@VasekPurchart could you check PR, please? Thx.

**Comment by VasekPurchart** [comment]
Fixed by #63
